[package]
name = "lgbm-sys-generator"
version = "0.0.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.65.1"
anyhow = "1.0.71"
doxygen-rs = "0.4"
